#                                     lug'at
soz = input("Biron-bir o'zbekcha so'z kiriting\n>>>")
if soz.lower() == 'buyuk':
    print(f"{soz.title()} so'zining inglizchasi great")
if soz.lower() == 'yaxshi':
    print(f"{soz.title()} so'zining inglizchasi good")
if soz.lower() == 'non':
    print(f"{soz.title()} so'zining inglizchasi bread")
if soz.lower() == 'suv':
    print(f"{soz.title()} so'zining inglizchasi water")
if soz.lower() == 'men':
    print(f"{soz.title()} so'zining inglizchasi I")
if soz.lower() == 'siz':
    print(f"{soz.title()} so'zining inglizchasi you")
if soz.lower() == 'biz':
    print(f"{soz.title()} so'zining inglizchasi we")
if soz.lower() == 'ular':
    print(f"{soz.title()} so'zining inglizchasi they")
if soz.lower() == 'uka':
    print(f"{soz.title()} so'zining inglizchasi brother")
if soz.lower() == 'aka':
    print(f"{soz.title()} so'zining inglizchasi brother")
if soz.lower() == 'opa':
    print(f"{soz.title()} so'zining inglizchasi sister")
if soz.lower() == 'singil':
    print(f"{soz.title()} so'zining inglizchasi sister")
if soz.lower() == "bolg'a":
    print(f"{soz.title()} so'zining inglizchasi hummer")
if soz.lower() == "do'st":
    print(f"{soz.title()} so'zining inglizchasi friend")
if soz.lower() == 'pul':
    print(f"{soz.title()} so'zining inglizchasi money")
if soz.lower() == 'oila':
    print(f"{soz.title()} so'zining inglizchasi family")
if soz.lower() == 'kim':
    print(f"{soz.title()} so'zining inglizchasi who")
if soz.lower() == 'mening':
    print(f"{soz.title()} so'zining inglizchasi my")
if soz.lower() == 'yashamoq':
    print(f"{soz.title()} so'zining inglizchasi live")
if soz.lower() == 'hayot':
    print(f"{soz.title()} so'zining inglizchasi life")
if soz.lower() == 'daraxt':
    print(f"{soz.title()} so'zining inglizchasi tree")
if soz.lower() == 'amaki':
    print(f"{soz.title()} so'zining inglizchasi uncle")
if soz.lower() == "tog'a":
    print(f"{soz.title()} so'zining inglizchasi uncle")
if soz.lower() == 'amma':
    print(f"{soz.title()} so'zining inglizchasi aunt")
if soz.lower() == 'hola':
    print(f"{soz.title()} so'zining inglizchasi aunt")
if soz.lower() == 'ism':
    print(f"{soz.title()} so'zining inglizchasi name")
if soz.lower() == 'familya':
    print(f"{soz.title()} so'zining inglizchasi surname")
if soz.lower() == "issiq":
    print(f"{soz.title()} so'zining inglizchasi hot")
if soz.lower() == "sovuq":
    print(f"{soz.title()} so'zining inglizchasi cold")
if soz.lower() == 'sumka':
    print(f"{soz.title()} so'zining inglizchasi bag")
if soz.lower() == 'penal':
    print(f"{soz.title()} so'zining inglizchasi pencil box")
if soz.lower() == 'kalta':
    print(f"{soz.title()} so'zining inglizchasi short")
if soz.lower() == 'dori':
    print(f"{soz.title()} so'zining inglizchasi remedy")
if soz.lower() == 'varoq':
    print(f"{soz.title()} so'zining inglizchasi paper")
if soz.lower() == 'futbolka':
    print(f"{soz.title()} so'zining inglizchasi t-shirt")
if soz.lower() == 'shim':
    print(f"{soz.title()} so'zining inglizchasi trousers")
if soz.lower() == 'osmon':
    print(f"{soz.title()} so'zining inglizchasi sky")
if soz.lower() == 'bulut':
    print(f"{soz.title()} so'zining inglizchasi cloud")
if soz.lower() == 'pichoq':
    print(f"{soz.title()} so'zining inglizchasi knife")
if soz.lower() == 'vilka':
    print(f"{soz.title()} so'zining inglizchasi fork")
if soz.lower() == 'qoshiq':
    print(f"{soz.title()} so'zining inglizchasi spoon")
if soz.lower() == 'lampochka':
    print(f"{soz.title()} so'zining inglizchasi lamp")
if soz.lower() == "kitob javoni":
    print(f"{soz.title()} so'zining inglizchasi bookshelf")
if soz.lower() == "harakat qilmoq":
    print(f"{soz.title()} so'zining inglizchasi try")
if soz.lower() == "chizg'ich":
    print(f"{soz.title()} so'zining inglizchasi rule")
if soz.lower() == "o'chirg'ich":
    print(f"{soz.title()} so'zining inglizchasi rubber")
if soz.lower() == 'toza':
    print(f"{soz.title()} so'zining inglizchasi clean")
if soz.lower() == 'ot':
    print(f"{soz.title()} so'zining inglizchasi horse")
if soz.lower() == "ko'ylar":
    print(f"{soz.title()} so'zining inglizchasi dress")
if soz.lower() == 'uzuk':
    print(f"{soz.title()} so'zining inglizchasi ring")
if soz.lower() == 'sochiq':
    print(f"{soz.title()} so'zining inglizchasi towel")
if soz.lower() == 'quvnoq':
    print(f"{soz.title()} so'zining inglizchasi cheerful")
if soz.lower() == 'xafa':
    print(f"{soz.title()} so'zining inglizchasi sad")
if soz.lower() == 'gul':
    print(f"{soz.title()} so'zining inglizchasi flower")
if soz.lower() == 'kelmoq':
    print(f"{soz.title()} so'zining inglizchasi come")
if soz.lower() == "olmoq":
    print(f"{soz.title()} so'zining inglizchasi take")
if soz.lower() == "multik":
    print(f"{soz.title()} so'zining inglizchasi cartoon")
if soz.lower() == "daftar":
    print(f"{soz.title()} so'zining inglizchasi notebook")
if soz.lower() == 'choynak':
    print(f"{soz.title()} so'zining inglizchasi tea-pot")
if soz.lower() == 'chashka':
    print(f"{soz.title()} so'zining inglizchasi cup")
if soz.lower() == 'televizor':
    print(f"{soz.title()} so'zining inglizchasi TV")
if soz.lower() == 'paypoq':
    print(f"{soz.title()} so'zining inglizchasi socks")
if soz.lower() == 'quti':
    print(f"{soz.title()} so'zining inglizchasi box")
if soz.lower() == 'paxta':
    print(f"{soz.title()} so'zining inglizchasi cotton")
if soz.lower() == 'tirnoq':
    print(f"{soz.title()} so'zining inglizchasi nail")
if soz.lower() == 'sakramoq':
    print(f"{soz.title()} so'zining inglizchasi jump")
if soz.lower() == 'kiyim javoni':
    print(f"{soz.title()} so'zining inglizchasi wardrobe")
if soz.lower() == 'jun':
    print(f"{soz.title()} so'zining inglizchasi wool")
if soz.lower() == "tozalovchi":
    print(f"{soz.title()} so'zining inglizchasi cleaner")
if soz.lower() == "tom":
    print(f"{soz.title()} so'zining inglizchasi roof")
if soz.lower() == "pol":
    print(f"{soz.title()} so'zining inglizchasi floor")
if soz.lower() == "ko'zgu":
    print(f"{soz.title()} so'zining inglizchasi mirror")
if soz.lower() == 'oyna':
    print(f"{soz.title()} so'zining inglizchasi window")
if soz.lower() == 'devor':
    print(f"{soz.title()} so'zining inglizchasi wall")
if soz.lower() == "o'simlik":
    print(f"{soz.title()} so'zining inglizchasi plant")
if soz.lower() == "o'smoq":
    print(f"{soz.title()} so'zining inglizchasi grow")
if soz.lower() == 'chiziq':
    print(f"{soz.title()} so'zining inglizchasi line")
if soz.lower() == 'uzum daraxti':
    print(f"{soz.title()} so'zining inglizchasi vine")
if soz.lower() == 'kapalak':
    print(f"{soz.title()} so'zining inglizchasi butterfly")
if soz.lower() == 'yulduz':
    print(f"{soz.title()} so'zining inglizchasi star")
if soz.lower() == "oy":
    print(f"{soz.title()} so'zining inglizchasi moon")
if soz.lower() == "ko'z":
    print(f"{soz.title()} so'zining inglizchasi eye")
if soz.lower() == "burun":
    print(f"{soz.title()} so'zining inglizchasi nose")
if soz.lower() == 'tufli':
    print(f"{soz.title()} so'zining inglizchasi shoes")
if soz.lower() == "ko'z oynak":
    print(f"{soz.title()} so'zining inglizchasi eyeglass")
if soz.lower() == 'kvartira':
    print(f"{soz.title()} so'zining inglizchasi flat")
if soz.lower() == 'shlyapa':
    print(f"{soz.title()} so'zining inglizchasi hat")
if soz.lower() == 'kepka':
    print(f"{soz.title()} so'zining inglizchasi cap")
if soz.lower() == 'chini':
    print(f"{soz.title()} so'zining inglizchasi bowl")
if soz.lower() == 'kanal':
    print(f"{soz.title()} so'zining inglizchasi channel")
if soz.lower() == 'skripka':
    print(f"{soz.title()} so'zining inglizchasi violin")
if soz.lower() == 'sartarosh':
    print(f"{soz.title()} so'zining inglizchasi barber(o'g'il bola)")
if soz.lower() == "sartarosh":
    print(f"{soz.title()} so'zining inglizchasi hair-dresser(qiz bola)")
if soz.lower() == "bakalashka":
    print(f"{soz.title()} so'zining inglizchasi bottle")
if soz.lower() == "atirgul":
    print(f"{soz.title()} so'zining inglizchasi rose")
if soz.lower() == "olma":
    print(f"{soz.title()} so'zining inglizchasi apple")
if soz.lower() == "future":
    print(f"{soz.title()} so'zining inglizchasi kelajak")
if soz.lower() == "gilam":
    print(f"{soz.title()} so'zining inglizchasi carpet")
if soz.lower() == "qon":
    print(f"{soz.title()} so'zining inglizchasi blood")
if soz.lower() == "ko'chirmoq":
    print(f"{soz.title()} so'zining inglizchasi copy")
if soz.lower() == 'tashqari':
    print(f"{soz.title()} so'zining inglizchasi outside")
if soz.lower() == 'ichkari':
    print(f"{soz.title()} so'zining inglizchasi inside")
if soz.lower() == "olov":
    print(f"{soz.title()} so'zining inglizchasi fire")
if soz.lower() == "kuylamoq":
    print(f"{soz.title()} so'zining inglizchasi sing")
if soz.lower() == 'yozmoq':
    print(f"{soz.title()} so'zining inglizchasi write")
if soz.lower() == 'haydamoq':
    print(f"{soz.title()} so'zining inglizchasi ride")
if soz.lower() == "o'ng":
    print(f"{soz.title()} so'zining inglizchasi right")
if soz.lower() == 'chap':
    print(f"{soz.title()} so'zining inglizchasi left")
if soz.lower() == "she'r":
    print(f"{soz.title()} so'zining inglizchasi poem")
if soz.lower() == "shoir":
    print(f"{soz.title()} so'zining inglizchasi poet")
if soz.lower() == "samolyot":
    print(f"{soz.title()} so'zining inglizchasi plane")
if soz.lower() == "o'qimoq":
    print(f"{soz.title()} so'zining inglizchasi read")
if soz.lower() == "gapirmoq":
    print(f"{soz.title()} so'zining inglizchasi speak")
if soz.lower() == 'raqam':
    print(f"{soz.title()} so'zining inglizchasi number")
if soz.lower() == 'sariq':
    print(f"{soz.title()} so'zining inglizchasi yellow")
if soz.lower() == 'yostiq':
    print(f"{soz.title()} so'zining inglizchasi pillow")
if soz.lower() == 'yashil':
    print(f"{soz.title()} so'zining inglizchasi green")
if soz.lower() == 'kulrang':
    print(f"{soz.title()} so'zining inglizchasi grey")
if soz.lower() == 'qizil':
    print(f"{soz.title()} so'zining inglizchasi red")
if soz.lower() == "qora":
    print(f"{soz.title()} so'zining inglizchasi black")
if soz.lower() == "ko'k":
    print(f"{soz.title()} so'zining inglizchasi blue")
if soz.lower() == "pushti":
    print(f"{soz.title()} so'zining inglizchasi pink")
if soz.lower() == 'sabzirang':
    print(f"{soz.title()} so'zining inglizchasi orange")
if soz.lower() == 'binafsharang':
    print(f"{soz.title()} so'zining inglizchasi violet")
if soz.lower() == "oq":
    print(f"{soz.title()} so'zining inglizchasi white")
if soz.lower() == "shaftoli":
    print(f"{soz.title()} so'zining inglizchasi peach")
if soz.lower() == 'nok':
    print(f"{soz.title()} so'zining inglizchasi pear")
if soz.lower() == 'gilos':
    print(f"{soz.title()} so'zining inglizchasi cherry")
if soz.lower() == 'idish javoni':
    print(f"{soz.title()} so'zining inglizchasi cupboard")
if soz.lower() == 'tualet':
    print(f"{soz.title()} so'zining inglizchasi toilet")
if soz.lower() == "vanna":
    print(f"{soz.title()} so'zining inglizchasi bath")
if soz.lower() == "xolodilnik":
    print(f"{soz.title()} so'zining inglizchasi fridge")
if soz.lower() == "gaz plitasi":
    print(f"{soz.title()} so'zining inglizchasi cooker")
if soz.lower() == 'matras':
    print(f"{soz.title()} so'zining inglizchasi mattress")
if soz.lower() == "to'shak":
    print(f"{soz.title()} so'zining inglizchasi mattress")
if soz.lower() == 'yahta':
    print(f"{soz.title()} so'zining inglizchasi yacht")
if soz.lower() == 'kema':
    print(f"{soz.title()} so'zining inglizchasi ship")
if soz.lower() == 'qamoq':
    print(f"{soz.title()} so'zining inglizchasi jail")
if soz.lower() == 'etik':
    print(f"{soz.title()} so'zining inglizchasi boot")
if soz.lower() == 'jemfer':
    print(f"{soz.title()} so'zining inglizchasi jamper")
if soz.lower() == 'kurtka':
    print(f"{soz.title()} so'zining inglizchasi jacket")
if soz.lower() == 'krosofka':
    print(f"{soz.title()} so'zining inglizchasi snickers")
if soz.lower() == 'kofta':
    print(f"{soz.title()} so'zining inglizchasi blouse")
if soz.lower() == "shippak":
    print(f"{soz.title()} so'zining inglizchasi slipper")
if soz.lower() == "uy hayvonlari":
    print(f"{soz.title()} so'zining inglizchasi domestic animals")
if soz.lower() == "quyon":
    print(f"{soz.title()} so'zining inglizchasi rabbit")
if soz.lower() == 'it':
    print(f"{soz.title()} so'zining inglizchasi dog")
if soz.lower() == "mushuk":
    print(f"{soz.title()} so'zining inglizchasi cat")
if soz.lower() == 'tovuq':
    print(f"{soz.title()} so'zining inglizchasi hen")
if soz.lower() == "xo'roz":
    print(f"{soz.title()} so'zining inglizchasi rooster")
if soz.lower() == "g'oz":
    print(f"{soz.title()} so'zining inglizchasi goose")
if soz.lower() == "o'rdak":
    print(f"{soz.title()} so'zining inglizchasi duck")
if soz.lower() == 'eshak':
    print(f"{soz.title()} so'zining inglizchasi donkey")
if soz.lower() == 'mol':
    print(f"{soz.title()} so'zining inglizchasi cow")
if soz.lower() == 'buzoq':
    print(f"{soz.title()} so'zining inglizchasi calf")
if soz.lower() == "ho'kiz":
    print(f"{soz.title()} so'zining inglizchasi bull")
if soz.lower() == "jo'ja":
    print(f"{soz.title()} so'zining inglizchasi chick")
if soz.lower() == "indyuk":
    print(f"{soz.title()} so'zining inglizchasi turkey")
if soz.lower() == "qo'zichoq":
    print(f"{soz.title()} so'zining inglizchasi lamb")
if soz.lower() == 'kuchukcha':
    print(f"{soz.title()} so'zining inglizchasi puppy")
if soz.lower() == "cho'chqa":
    print(f"{soz.title()} so'zining inglizchasi pig")
if soz.lower() == 'mushukcha':
    print(f"{soz.title()} so'zining inglizchasi kitten")
if soz.lower() == "qo'y":
    print(f"{soz.title()} so'zining inglizchasi ship")
if soz.lower() == 'yovvoyi hayvonlar':
    print(f"{soz.title()} so'zining inglizchasi vild animals")
if soz.lower() == "yo'lbars":
    print(f"{soz.title()} so'zining inglizchasi tiger")
if soz.lower() == 'sher':
    print(f"{soz.title()} so'zining inglizchasi lion")
if soz.lower() == 'jirafa':
    print(f"{soz.title()} so'zining inglizchasi giraffe")
if soz.lower() == 'ayiq':
    print(f"{soz.title()} so'zining inglizchasi bear")
if soz.lower() == 'tumsoh':
    print(f"{soz.title()} so'zining inglizchasi crocodile")
if soz.lower() == "tulki":
    print(f"{soz.title()} so'zining inglizchasi fox")
if soz.lower() == "bo'ri":
    print(f"{soz.title()} so'zining inglizchasi wolf")
if soz.lower() == 'gepard':
    print(f"{soz.title()} so'zining inglizchasi leopard")
if soz.lower() == "bug'u":
    print(f"{soz.title()} so'zining inglizchasi deer")
if soz.lower() == "maymun":
    print(f"{soz.title()} so'zining inglizchasi ape")
if soz.lower() == 'dasturxon':
    print(f"{soz.title()} so'zining inglizchasi table cloth")
if soz.lower() == "non":
    print(f"{soz.title()} so'zining inglizchasi bread")
if soz.lower() == "pechenye":
    print(f"{soz.title()} so'zining inglizchasi bisquit")
if soz.lower() == "qosh":
    print(f"{soz.title()} so'zining inglizchasi eyebrow")
if soz.lower() == "mayka":
    print(f"{soz.title()} so'zining inglizchasi underwear")
if soz.lower() == "yugurmoq":
    print(f"{soz.title()} so'zining inglizchasi run")
if soz.lower() == "o'tirmoq":
    print(f"{soz.title()} so'zining inglizchasi sit")
if soz.lower() == 'uhlamoq':
    print(f"{soz.title()} so'zining inglizchasi sleep")
if soz.lower() == 'chizmoq':
    print(f"{soz.title()} so'zining inglizchasi draw")
if soz.lower() == 'kulmoq':
    print(f"{soz.title()} so'zining inglizchasi smile")
if soz.lower() == "yig'lamoq":
    print(f"{soz.title()} so'zining inglizchasi cry")
if soz.lower() == 'turmoq':
    print(f"{soz.title()} so'zining inglizchasi stand")
if soz.lower() == "yotmoq":
    print(f"{soz.title()} so'zining inglizchasi lay")
if soz.lower() == "yemoq":
    print(f"{soz.title()} so'zining inglizchasi eat")
if soz.lower() == "ichmoq":
    print(f"{soz.title()} so'zining inglizchasi drink")
if soz.lower() == 'chaqirmoq':
    print(f"{soz.title()} so'zining inglizchasi call")
if soz.lower() == 'baqirmoq':
    print(f"{soz.title()} so'zining inglizchasi shout, cry")
if soz.lower() == "suzmoq":
    print(f"{soz.title()} so'zining inglizchasi swim")
if soz.lower() == "kovlamoq":
    print(f"{soz.title()} so'zining inglizchasi dig")
if soz.lower() == "ko'rmoq":
    print(f"{soz.title()} so'zining inglizchasi watch")
if soz.lower() == 'qaramoq':
    print(f"{soz.title()} so'zining inglizchasi look")
if soz.lower() == 'qovun':
    print(f"{soz.title()} so'zining inglizchasi melon")
if soz.lower() == 'ovlamoq':
    print(f"{soz.title()} so'zining inglizchasi hunt")
if soz.lower() == "tarvuz":
    print(f"{soz.title()} so'zining inglizchasi water-melon")
if soz.lower() == "qulupnay":
    print(f"{soz.title()} so'zining inglizchasi strawberri")
if soz.lower() == "kartoshka":
    print(f"{soz.title()} so'zining inglizchasi potato")
if soz.lower() == 'pomidor':
    print(f"{soz.title()} so'zining inglizchasi tomato")
if soz.lower() == "karam":
    print(f"{soz.title()} so'zining inglizchasi kabbage")
if soz.lower() == 'sabzi':
    print(f"{soz.title()} so'zining inglizchasi carrot")
if soz.lower() == 'quyosh':
    print(f"{soz.title()} so'zining inglizchasi sun")
if soz.lower() == 'tish':
    print(f"{soz.title()} so'zining inglizchasi tooth")
if soz.lower() == 'lab':
    print(f"{soz.title()} so'zining inglizchasi lip")
if soz.lower() == 'quloq':
    print(f"{soz.title()} so'zining inglizchasi ear")
if soz.lower() == 'apelsin':
    print(f"{soz.title()} so'zining inglizchasi orange")
if soz.lower() == "yomg'ir":
    print(f"{soz.title()} so'zining inglizchasi rain")
if soz.lower() == 'anjir':
    print(f"{soz.title()} so'zining inglizchasi fig")
if soz.lower() == "sharf":
    print(f"{soz.title()} so'zining inglizchasi scarf")
if soz.lower() == "chang":
    print(f"{soz.title()} so'zining inglizchasi dust")
if soz.lower() == "buta":
    print(f"{soz.title()} so'zining inglizchasi bush")
if soz.lower() == "og'iz":
    print(f"{soz.title()} so'zining inglizchasi mouth")
if soz.lower() == "pult":
    print(f"{soz.title()} so'zining inglizchasi remote control")
if soz.lower() == 'ob-havo':
    print(f"{soz.title()} so'zining inglizchasi weather")
if soz.lower() == "momaqaldiroq":
    print(f"{soz.title()} so'zining inglizchasi thunder")
if soz.lower() == "chaqmoq":
    print(f"{soz.title()} so'zining inglizchasi lightning")
if soz.lower() == "muz":
    print(f"{soz.title()} so'zining inglizchasi ice")
if soz.lower() == 'yer':
    print(f"{soz.title()} so'zining inglizchasi earth")
if soz.lower() == "havo":
    print(f"{soz.title()} so'zining inglizchasi air")
if soz.lower() == 'tun':
    print(f"{soz.title()} so'zining inglizchasi night")
if soz.lower() == "kun":
    print(f"{soz.title()} so'zining inglizchasi day")
if soz.lower() == "qorong'ulik":
    print(f"{soz.title()} so'zining inglizchasi darkness")
if soz.lower() == "qo'rqinchli":
    print(f"{soz.title()} so'zining inglizchasi terrible")
if soz.lower() == "qo'rqinchli":
    print(f"{soz.title()} so'zining inglizchasi horrible")
if soz.lower() == 'xavfli':
    print(f"{soz.title()} so'zining inglizchasi dangerous")
if soz.lower() == "qor":
    print(f"{soz.title()} so'zining inglizchasi snow")
if soz.lower() == "to'qimoq":
    print(f"{soz.title()} so'zining inglizchasi knit")
if soz.lower() == "savdo":
    print(f"{soz.title()} so'zining inglizchasi trade")
if soz.lower() == 'limon':
    print(f"{soz.title()} so'zining inglizchasi lemon")
if soz.lower() == "pechka":
    print(f"{soz.title()} so'zining inglizchasi oven")
if soz.lower() == 'bilakuzuk':
    print(f"{soz.title()} so'zining inglizchasi braclet")
if soz.lower() == 'sipochka':
    print(f"{soz.title()} so'zining inglizchasi necklace")
yana_soz = input("Yana so'z kiritasizmi? (Ha yoki Yoq):")
if yana_soz.lower() != 'ha':
    print("Bizning dasturdan foydalanganingiz uchun raxmat!")
else:
    soz = input("Biron-bir o'zbekcha so'z kiriting\n>>>")
    if soz.lower() == 'buyuk':
        print(f"{soz.title()} so'zining inglizchasi great")
if soz.lower() == 'yaxshi':
    print(f"{soz.title()} so'zining inglizchasi good")
if soz.lower() == 'non':
    print(f"{soz.title()} so'zining inglizchasi bread")
if soz.lower() == 'suv':
    print(f"{soz.title()} so'zining inglizchasi water")
if soz.lower() == 'men':
    print(f"{soz.title()} so'zining inglizchasi I")
if soz.lower() == 'siz':
    print(f"{soz.title()} so'zining inglizchasi you")
if soz.lower() == 'biz':
    print(f"{soz.title()} so'zining inglizchasi we")
if soz.lower() == 'ular':
    print(f"{soz.title()} so'zining inglizchasi they")
if soz.lower() == 'uka':
    print(f"{soz.title()} so'zining inglizchasi brother")
if soz.lower() == 'aka':
    print(f"{soz.title()} so'zining inglizchasi brother")
if soz.lower() == 'opa':
    print(f"{soz.title()} so'zining inglizchasi sister")
if soz.lower() == 'singil':
    print(f"{soz.title()} so'zining inglizchasi sister")
if soz.lower() == "bolg'a":
    print(f"{soz.title()} so'zining inglizchasi hummer")
if soz.lower() == "do'st":
    print(f"{soz.title()} so'zining inglizchasi friend")
if soz.lower() == 'pul':
    print(f"{soz.title()} so'zining inglizchasi money")
if soz.lower() == 'oila':
    print(f"{soz.title()} so'zining inglizchasi family")
if soz.lower() == 'kim':
    print(f"{soz.title()} so'zining inglizchasi who")
if soz.lower() == 'mening':
    print(f"{soz.title()} so'zining inglizchasi my")
if soz.lower() == 'yashamoq':
    print(f"{soz.title()} so'zining inglizchasi live")
if soz.lower() == 'hayot':
    print(f"{soz.title()} so'zining inglizchasi life")
if soz.lower() == 'daraxt':
    print(f"{soz.title()} so'zining inglizchasi tree")
if soz.lower() == 'amaki':
    print(f"{soz.title()} so'zining inglizchasi uncle")
if soz.lower() == "tog'a":
    print(f"{soz.title()} so'zining inglizchasi uncle")
if soz.lower() == 'amma':
    print(f"{soz.title()} so'zining inglizchasi aunt")
if soz.lower() == 'hola':
    print(f"{soz.title()} so'zining inglizchasi aunt")
if soz.lower() == 'ism':
    print(f"{soz.title()} so'zining inglizchasi name")
if soz.lower() == 'familya':
    print(f"{soz.title()} so'zining inglizchasi surname")
if soz.lower() == "issiq":
    print(f"{soz.title()} so'zining inglizchasi hot")
if soz.lower() == "sovuq":
    print(f"{soz.title()} so'zining inglizchasi cold")
if soz.lower() == 'sumka':
    print(f"{soz.title()} so'zining inglizchasi bag")
if soz.lower() == 'penal':
    print(f"{soz.title()} so'zining inglizchasi pencil box")
if soz.lower() == 'kalta':
    print(f"{soz.title()} so'zining inglizchasi short")
if soz.lower() == 'dori':
    print(f"{soz.title()} so'zining inglizchasi remedy")
if soz.lower() == 'varoq':
    print(f"{soz.title()} so'zining inglizchasi paper")
if soz.lower() == 'futbolka':
    print(f"{soz.title()} so'zining inglizchasi t-shirt")
if soz.lower() == 'shim':
    print(f"{soz.title()} so'zining inglizchasi trousers")
if soz.lower() == 'osmon':
    print(f"{soz.title()} so'zining inglizchasi sky")
if soz.lower() == 'bulut':
    print(f"{soz.title()} so'zining inglizchasi cloud")
if soz.lower() == 'pichoq':
    print(f"{soz.title()} so'zining inglizchasi knife")
if soz.lower() == 'vilka':
    print(f"{soz.title()} so'zining inglizchasi fork")
if soz.lower() == 'qoshiq':
    print(f"{soz.title()} so'zining inglizchasi spoon")
if soz.lower() == 'lampochka':
    print(f"{soz.title()} so'zining inglizchasi lamp")
if soz.lower() == "kitob javoni":
    print(f"{soz.title()} so'zining inglizchasi bookshelf")
if soz.lower() == "harakat qilmoq":
    print(f"{soz.title()} so'zining inglizchasi try")
if soz.lower() == "chizg'ich":
    print(f"{soz.title()} so'zining inglizchasi rule")
if soz.lower() == "o'chirg'ich":
    print(f"{soz.title()} so'zining inglizchasi rubber")
if soz.lower() == 'toza':
    print(f"{soz.title()} so'zining inglizchasi clean")
if soz.lower() == 'ot':
    print(f"{soz.title()} so'zining inglizchasi horse")
if soz.lower() == "ko'ylar":
    print(f"{soz.title()} so'zining inglizchasi dress")
if soz.lower() == 'uzuk':
    print(f"{soz.title()} so'zining inglizchasi ring")
if soz.lower() == 'sochiq':
    print(f"{soz.title()} so'zining inglizchasi towel")
if soz.lower() == 'quvnoq':
    print(f"{soz.title()} so'zining inglizchasi cheerful")
if soz.lower() == 'xafa':
    print(f"{soz.title()} so'zining inglizchasi sad")
if soz.lower() == 'gul':
    print(f"{soz.title()} so'zining inglizchasi flower")
if soz.lower() == 'kelmoq':
    print(f"{soz.title()} so'zining inglizchasi come")
if soz.lower() == "olmoq":
    print(f"{soz.title()} so'zining inglizchasi take")
if soz.lower() == "multik":
    print(f"{soz.title()} so'zining inglizchasi cartoon")
if soz.lower() == "daftar":
    print(f"{soz.title()} so'zining inglizchasi notebook")
if soz.lower() == 'choynak':
    print(f"{soz.title()} so'zining inglizchasi tea-pot")
if soz.lower() == 'chashka':
    print(f"{soz.title()} so'zining inglizchasi cup")
if soz.lower() == 'televizor':
    print(f"{soz.title()} so'zining inglizchasi TV")
if soz.lower() == 'paypoq':
    print(f"{soz.title()} so'zining inglizchasi socks")
if soz.lower() == 'quti':
    print(f"{soz.title()} so'zining inglizchasi box")
if soz.lower() == 'paxta':
    print(f"{soz.title()} so'zining inglizchasi cotton")
if soz.lower() == 'tirnoq':
    print(f"{soz.title()} so'zining inglizchasi nail")
if soz.lower() == 'sakramoq':
    print(f"{soz.title()} so'zining inglizchasi jump")
if soz.lower() == 'kiyim javoni':
    print(f"{soz.title()} so'zining inglizchasi wardrobe")
if soz.lower() == 'jun':
    print(f"{soz.title()} so'zining inglizchasi wool")
if soz.lower() == "tozalovchi":
    print(f"{soz.title()} so'zining inglizchasi cleaner")
if soz.lower() == "tom":
    print(f"{soz.title()} so'zining inglizchasi roof")
if soz.lower() == "pol":
    print(f"{soz.title()} so'zining inglizchasi floor")
if soz.lower() == "ko'zgu":
    print(f"{soz.title()} so'zining inglizchasi mirror")
if soz.lower() == 'oyna':
    print(f"{soz.title()} so'zining inglizchasi window")
if soz.lower() == 'devor':
    print(f"{soz.title()} so'zining inglizchasi wall")
if soz.lower() == "o'simlik":
    print(f"{soz.title()} so'zining inglizchasi plant")
if soz.lower() == "o'smoq":
    print(f"{soz.title()} so'zining inglizchasi grow")
if soz.lower() == 'chiziq':
    print(f"{soz.title()} so'zining inglizchasi line")
if soz.lower() == 'uzum daraxti':
    print(f"{soz.title()} so'zining inglizchasi vine")
if soz.lower() == 'kapalak':
    print(f"{soz.title()} so'zining inglizchasi butterfly")
if soz.lower() == 'yulduz':
    print(f"{soz.title()} so'zining inglizchasi star")
if soz.lower() == "oy":
    print(f"{soz.title()} so'zining inglizchasi moon")
if soz.lower() == "ko'z":
    print(f"{soz.title()} so'zining inglizchasi eye")
if soz.lower() == "burun":
    print(f"{soz.title()} so'zining inglizchasi nose")
if soz.lower() == 'tufli':
    print(f"{soz.title()} so'zining inglizchasi shoes")
if soz.lower() == "ko'z oynak":
    print(f"{soz.title()} so'zining inglizchasi eyeglass")
if soz.lower() == 'kvartira':
    print(f"{soz.title()} so'zining inglizchasi flat")
if soz.lower() == 'shlyapa':
    print(f"{soz.title()} so'zining inglizchasi hat")
if soz.lower() == 'kepka':
    print(f"{soz.title()} so'zining inglizchasi cap")
if soz.lower() == 'chini':
    print(f"{soz.title()} so'zining inglizchasi bowl")
if soz.lower() == 'kanal':
    print(f"{soz.title()} so'zining inglizchasi channel")
if soz.lower() == 'skripka':
    print(f"{soz.title()} so'zining inglizchasi violin")
if soz.lower() == 'sartarosh':
    print(f"{soz.title()} so'zining inglizchasi barber(o'g'il bola)")
if soz.lower() == "sartarosh":
    print(f"{soz.title()} so'zining inglizchasi hair-dresser(qiz bola)")
if soz.lower() == "bakalashka":
    print(f"{soz.title()} so'zining inglizchasi bottle")
if soz.lower() == "atirgul":
    print(f"{soz.title()} so'zining inglizchasi rose")
if soz.lower() == "olma":
    print(f"{soz.title()} so'zining inglizchasi apple")
if soz.lower() == "future":
    print(f"{soz.title()} so'zining inglizchasi kelajak")
if soz.lower() == "gilam":
    print(f"{soz.title()} so'zining inglizchasi carpet")
if soz.lower() == "qon":
    print(f"{soz.title()} so'zining inglizchasi blood")
if soz.lower() == "ko'chirmoq":
    print(f"{soz.title()} so'zining inglizchasi copy")
if soz.lower() == 'tashqari':
    print(f"{soz.title()} so'zining inglizchasi outside")
if soz.lower() == 'ichkari':
    print(f"{soz.title()} so'zining inglizchasi inside")
if soz.lower() == "olov":
    print(f"{soz.title()} so'zining inglizchasi fire")
if soz.lower() == "kuylamoq":
    print(f"{soz.title()} so'zining inglizchasi sing")
if soz.lower() == 'yozmoq':
    print(f"{soz.title()} so'zining inglizchasi write")
if soz.lower() == 'haydamoq':
    print(f"{soz.title()} so'zining inglizchasi ride")
if soz.lower() == "o'ng":
    print(f"{soz.title()} so'zining inglizchasi right")
if soz.lower() == 'chap':
    print(f"{soz.title()} so'zining inglizchasi left")
if soz.lower() == "she'r":
    print(f"{soz.title()} so'zining inglizchasi poem")
if soz.lower() == "shoir":
    print(f"{soz.title()} so'zining inglizchasi poet")
if soz.lower() == "samolyot":
    print(f"{soz.title()} so'zining inglizchasi plane")
if soz.lower() == "o'qimoq":
    print(f"{soz.title()} so'zining inglizchasi read")
if soz.lower() == "gapirmoq":
    print(f"{soz.title()} so'zining inglizchasi speak")
if soz.lower() == 'raqam':
    print(f"{soz.title()} so'zining inglizchasi number")
if soz.lower() == 'sariq':
    print(f"{soz.title()} so'zining inglizchasi yellow")
if soz.lower() == 'yostiq':
    print(f"{soz.title()} so'zining inglizchasi pillow")
if soz.lower() == 'yashil':
    print(f"{soz.title()} so'zining inglizchasi green")
if soz.lower() == 'kulrang':
    print(f"{soz.title()} so'zining inglizchasi grey")
if soz.lower() == 'qizil':
    print(f"{soz.title()} so'zining inglizchasi red")
if soz.lower() == "qora":
    print(f"{soz.title()} so'zining inglizchasi black")
if soz.lower() == "ko'k":
    print(f"{soz.title()} so'zining inglizchasi blue")
if soz.lower() == "pushti":
    print(f"{soz.title()} so'zining inglizchasi pink")
if soz.lower() == 'sabzirang':
    print(f"{soz.title()} so'zining inglizchasi orange")
if soz.lower() == 'binafsharang':
    print(f"{soz.title()} so'zining inglizchasi violet")
if soz.lower() == "oq":
    print(f"{soz.title()} so'zining inglizchasi white")
if soz.lower() == "shaftoli":
    print(f"{soz.title()} so'zining inglizchasi peach")
if soz.lower() == 'nok':
    print(f"{soz.title()} so'zining inglizchasi pear")
if soz.lower() == 'gilos':
    print(f"{soz.title()} so'zining inglizchasi cherry")
if soz.lower() == 'idish javoni':
    print(f"{soz.title()} so'zining inglizchasi cupboard")
if soz.lower() == 'tualet':
    print(f"{soz.title()} so'zining inglizchasi toilet")
if soz.lower() == "vanna":
    print(f"{soz.title()} so'zining inglizchasi bath")
if soz.lower() == "xolodilnik":
    print(f"{soz.title()} so'zining inglizchasi fridge")
if soz.lower() == "gaz plitasi":
    print(f"{soz.title()} so'zining inglizchasi cooker")
if soz.lower() == 'matras':
    print(f"{soz.title()} so'zining inglizchasi mattress")
if soz.lower() == "to'shak":
    print(f"{soz.title()} so'zining inglizchasi mattress")
if soz.lower() == 'yahta':
    print(f"{soz.title()} so'zining inglizchasi yacht")
if soz.lower() == 'kema':
    print(f"{soz.title()} so'zining inglizchasi ship")
if soz.lower() == 'qamoq':
    print(f"{soz.title()} so'zining inglizchasi jail")
if soz.lower() == 'etik':
    print(f"{soz.title()} so'zining inglizchasi boot")
if soz.lower() == 'jemfer':
    print(f"{soz.title()} so'zining inglizchasi jamper")
if soz.lower() == 'kurtka':
    print(f"{soz.title()} so'zining inglizchasi jacket")
if soz.lower() == 'krosofka':
    print(f"{soz.title()} so'zining inglizchasi snickers")
if soz.lower() == 'kofta':
    print(f"{soz.title()} so'zining inglizchasi blouse")
if soz.lower() == "shippak":
    print(f"{soz.title()} so'zining inglizchasi slipper")
if soz.lower() == "uy hayvonlari":
    print(f"{soz.title()} so'zining inglizchasi domestic animals")
if soz.lower() == "quyon":
    print(f"{soz.title()} so'zining inglizchasi rabbit")
if soz.lower() == 'it':
    print(f"{soz.title()} so'zining inglizchasi dog")
if soz.lower() == "mushuk":
    print(f"{soz.title()} so'zining inglizchasi cat")
if soz.lower() == 'tovuq':
    print(f"{soz.title()} so'zining inglizchasi hen")
if soz.lower() == "xo'roz":
    print(f"{soz.title()} so'zining inglizchasi rooster")
if soz.lower() == "g'oz":
    print(f"{soz.title()} so'zining inglizchasi goose")
if soz.lower() == "o'rdak":
    print(f"{soz.title()} so'zining inglizchasi duck")
if soz.lower() == 'eshak':
    print(f"{soz.title()} so'zining inglizchasi donkey")
if soz.lower() == 'mol':
    print(f"{soz.title()} so'zining inglizchasi cow")
if soz.lower() == 'buzoq':
    print(f"{soz.title()} so'zining inglizchasi calf")
if soz.lower() == "ho'kiz":
    print(f"{soz.title()} so'zining inglizchasi bull")
if soz.lower() == "jo'ja":
    print(f"{soz.title()} so'zining inglizchasi chick")
if soz.lower() == "indyuk":
    print(f"{soz.title()} so'zining inglizchasi turkey")
if soz.lower() == "qo'zichoq":
    print(f"{soz.title()} so'zining inglizchasi lamb")
if soz.lower() == 'kuchukcha':
    print(f"{soz.title()} so'zining inglizchasi puppy")
if soz.lower() == "cho'chqa":
    print(f"{soz.title()} so'zining inglizchasi pig")
if soz.lower() == 'mushukcha':
    print(f"{soz.title()} so'zining inglizchasi kitten")
if soz.lower() == "qo'y":
    print(f"{soz.title()} so'zining inglizchasi ship")
if soz.lower() == 'yovvoyi hayvonlar':
    print(f"{soz.title()} so'zining inglizchasi vild animals")
if soz.lower() == "yo'lbars":
    print(f"{soz.title()} so'zining inglizchasi tiger")
if soz.lower() == 'sher':
    print(f"{soz.title()} so'zining inglizchasi lion")
if soz.lower() == 'jirafa':
    print(f"{soz.title()} so'zining inglizchasi giraffe")
if soz.lower() == 'ayiq':
    print(f"{soz.title()} so'zining inglizchasi bear")
if soz.lower() == 'tumsoh':
    print(f"{soz.title()} so'zining inglizchasi crocodile")
if soz.lower() == "tulki":
    print(f"{soz.title()} so'zining inglizchasi fox")
if soz.lower() == "bo'ri":
    print(f"{soz.title()} so'zining inglizchasi wolf")
if soz.lower() == 'gepard':
    print(f"{soz.title()} so'zining inglizchasi leopard")
if soz.lower() == "bug'u":
    print(f"{soz.title()} so'zining inglizchasi deer")
if soz.lower() == "maymun":
    print(f"{soz.title()} so'zining inglizchasi ape")
if soz.lower() == 'dasturxon':
    print(f"{soz.title()} so'zining inglizchasi table cloth")
if soz.lower() == "non":
    print(f"{soz.title()} so'zining inglizchasi bread")
if soz.lower() == "pechenye":
    print(f"{soz.title()} so'zining inglizchasi bisquit")
if soz.lower() == "qosh":
    print(f"{soz.title()} so'zining inglizchasi eyebrow")
if soz.lower() == "mayka":
    print(f"{soz.title()} so'zining inglizchasi underwear")
if soz.lower() == "yugurmoq":
    print(f"{soz.title()} so'zining inglizchasi run")
if soz.lower() == "o'tirmoq":
    print(f"{soz.title()} so'zining inglizchasi sit")
if soz.lower() == 'uhlamoq':
    print(f"{soz.title()} so'zining inglizchasi sleep")
if soz.lower() == 'chizmoq':
    print(f"{soz.title()} so'zining inglizchasi draw")
if soz.lower() == 'kulmoq':
    print(f"{soz.title()} so'zining inglizchasi smile")
if soz.lower() == "yig'lamoq":
    print(f"{soz.title()} so'zining inglizchasi cry")
if soz.lower() == 'turmoq':
    print(f"{soz.title()} so'zining inglizchasi stand")
if soz.lower() == "yotmoq":
    print(f"{soz.title()} so'zining inglizchasi lay")
if soz.lower() == "yemoq":
    print(f"{soz.title()} so'zining inglizchasi eat")
if soz.lower() == "ichmoq":
    print(f"{soz.title()} so'zining inglizchasi drink")
if soz.lower() == 'chaqirmoq':
    print(f"{soz.title()} so'zining inglizchasi call")
if soz.lower() == 'baqirmoq':
    print(f"{soz.title()} so'zining inglizchasi shout, cry")
if soz.lower() == "suzmoq":
    print(f"{soz.title()} so'zining inglizchasi swim")
if soz.lower() == "kovlamoq":
    print(f"{soz.title()} so'zining inglizchasi dig")
if soz.lower() == "ko'rmoq":
    print(f"{soz.title()} so'zining inglizchasi watch")
if soz.lower() == 'qaramoq':
    print(f"{soz.title()} so'zining inglizchasi look")
if soz.lower() == 'qovun':
    print(f"{soz.title()} so'zining inglizchasi melon")
if soz.lower() == 'ovlamoq':
    print(f"{soz.title()} so'zining inglizchasi hunt")
if soz.lower() == "tarvuz":
    print(f"{soz.title()} so'zining inglizchasi water-melon")
if soz.lower() == "qulupnay":
    print(f"{soz.title()} so'zining inglizchasi strawberri")
if soz.lower() == "kartoshka":
    print(f"{soz.title()} so'zining inglizchasi potato")
if soz.lower() == 'pomidor':
    print(f"{soz.title()} so'zining inglizchasi tomato")
if soz.lower() == "karam":
    print(f"{soz.title()} so'zining inglizchasi kabbage")
if soz.lower() == 'sabzi':
    print(f"{soz.title()} so'zining inglizchasi carrot")
if soz.lower() == 'quyosh':
    print(f"{soz.title()} so'zining inglizchasi sun")
if soz.lower() == 'tish':
    print(f"{soz.title()} so'zining inglizchasi tooth")
if soz.lower() == 'lab':
    print(f"{soz.title()} so'zining inglizchasi lip")
if soz.lower() == 'quloq':
    print(f"{soz.title()} so'zining inglizchasi ear")
if soz.lower() == 'apelsin':
    print(f"{soz.title()} so'zining inglizchasi orange")
if soz.lower() == "yomg'ir":
    print(f"{soz.title()} so'zining inglizchasi rain")
if soz.lower() == 'anjir':
    print(f"{soz.title()} so'zining inglizchasi fig")
if soz.lower() == "sharf":
    print(f"{soz.title()} so'zining inglizchasi scarf")
if soz.lower() == "chang":
    print(f"{soz.title()} so'zining inglizchasi dust")
if soz.lower() == "buta":
    print(f"{soz.title()} so'zining inglizchasi bush")
if soz.lower() == "og'iz":
    print(f"{soz.title()} so'zining inglizchasi mouth")
if soz.lower() == "pult":
    print(f"{soz.title()} so'zining inglizchasi remote control")
if soz.lower() == 'ob-havo':
    print(f"{soz.title()} so'zining inglizchasi weather")
if soz.lower() == "momaqaldiroq":
    print(f"{soz.title()} so'zining inglizchasi thunder")
if soz.lower() == "chaqmoq":
    print(f"{soz.title()} so'zining inglizchasi lightning")
if soz.lower() == "muz":
    print(f"{soz.title()} so'zining inglizchasi ice")
if soz.lower() == 'yer':
    print(f"{soz.title()} so'zining inglizchasi earth")
if soz.lower() == "havo":
    print(f"{soz.title()} so'zining inglizchasi air")
if soz.lower() == 'tun':
    print(f"{soz.title()} so'zining inglizchasi night")
if soz.lower() == "kun":
    print(f"{soz.title()} so'zining inglizchasi day")
if soz.lower() == "qorong'ulik":
    print(f"{soz.title()} so'zining inglizchasi darkness")
if soz.lower() == "qo'rqinchli":
    print(f"{soz.title()} so'zining inglizchasi terrible")
if soz.lower() == "qo'rqinchli":
    print(f"{soz.title()} so'zining inglizchasi horrible")
if soz.lower() == 'xavfli':
    print(f"{soz.title()} so'zining inglizchasi dangerous")
if soz.lower() == "qor":
    print(f"{soz.title()} so'zining inglizchasi snow")
if soz.lower() == "to'qimoq":
    print(f"{soz.title()} so'zining inglizchasi knit")
if soz.lower() == "savdo":
    print(f"{soz.title()} so'zining inglizchasi trade")
if soz.lower() == 'limon':
    print(f"{soz.title()} so'zining inglizchasi lemon")
if soz.lower() == "pechka":
    print(f"{soz.title()} so'zining inglizchasi oven")
if soz.lower() == 'bilakuzuk':
    print(f"{soz.title()} so'zining inglizchasi braclet")
if soz.lower() == 'sipochka':
    print(f"{soz.title()} so'zining inglizchasi necklace")





